### PR TITLE
asd

### LINKED ISSUE #15: Hotkeys don't work on Windows with non en-us locale
Current way of matching hotkey with `event.key` property leads to broken hotkeys on Windows (Chrome, Vivaldi at least) as, for example with ru-RU locale on keybord hitting cmd+b will send event with `key` property set to cyrillic "и" and not "b".

First it was found in https://github.com/umputun/remark/issues/404

Images provided by @Andrew-Shtein prove difference in `key` prop

Issue located here:
https://github.com/github/markdown-toolbar-element/blob/dd0ffba8d9ad9d64471d3be41b3b7e1b77aa3545/index.js#L228-L236

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #15

### CODE REVIEW

**Comment by keithamus** [comment]
Sadly `event.code` will not work in this instance because alternative layouts such as Dvorak misreport their key. For example in Dvorak, pushing `x` will result in `KeyB` while pushing `b` will result in `KeyB` also.

I'll close this PR as it will introduce new bugs which we've already fixed prior. I welcome new ideas to fix this though!

**Comment by afwn90cj93201nixr2e1re** [comment]
Em, is that really problem? It's their implementation problem's.

**Comment by keithamus** [comment]
I am not referring to an implementation, but the underlying mechanics of `event.code` - it specifies the keyboard character which means it does not support switching layouts. The same is true of any alternate layout, not just specific ones. We made a switch _from_ `event.code` to `event.key` to solve precisely this bug.

**Comment by afwn90cj93201nixr2e1re** [comment]
btw .code is newer than key, so, i think key gonna be deprecated soon.

**Comment by afwn90cj93201nixr2e1re** [comment]
Maybe we should just make detector?

**Comment by keithamus** [comment]
Happy to explore ideas. I'm not sure how a detector could be made. You could compare `code` and `key`, and if there's a discrepency, then... I'm not sure how you'd resolve that?

**Comment by afwn90cj93201nixr2e1re** [comment]
Yep, as u suggested. Just try to emulate key press, and check what's going on.

https://github.com/ahtcx/layoutline
btw it's also just piece of shit, u r right.

**Pull request closed without merging**
